name: terraform-abacao
version: 0.11.10
summary: Terraform - Infrastructure-as-Code AB
description: |
  Terraform is a tool from Hashicorp for building, changing, and versioning
  infrastructure safely and efficiently. Terraform can manage existing and
  popular service providers as well as custom in-house solutions.

grade: stable
confinement: classic

architectures: [amd64]

apps:
  terraform:
    command: bin/terraform
    plugs: [home, network]
    aliases: [ terraform ]

parts:
  terraform:
    source: https://github.com/hashicorp/terraform.git
    source-tag: 0.11.10
    plugin: go
    go-importpath: github.com/hashicorp/terraform
    go-packages: [github.com/hashicorp/terraform]
    go-buildtags: [core]
    after: [go]
  go:
    source-tag: go1.11.2
